### ISSUE TITLE
Bug in JAR file

### ISSUE THREAD

**Issue by ChongCheeKaiClarence** [nus-cs2103-AY2223S1/forum#284] opened 2022-09-21 07:15 UTC
I tried the input `deadline deadline`, and I got this error message in my JAR file.

But this error does not occur when I run the launcher from the launcher class.

![image](https://user-images.githubusercontent.com/97396452/191438937-1c22b98b-b1ac-4747-a338-c213b2a54582.png)

**Comment by RussellDash332** [comment] 2022-09-21 08:15
I downloaded your `v0.2` jar and clicked on it directly, `deadline deadline` already gave me an error even when you specify the `build.gradle` correctly...

**Comment by rui-han-crh** [comment] 2022-09-21 08:31
Hi, InvocationTargetException is usually caused by javafx throwing another exception on top of an exception that your program threw. In this case, it seems there is a missing check that the array of elements needed to construct a Deadline must be more than 1 when invoking the creation of a new Deadline.

On line 221 of the `TaskList` class, it is assumed that `deadlineComponents` will contain elements 0 and 1 when split by the `/by` delimiter. But with outputs that don't contain the `/by` delimiter, there is only 1 element, so index 1 doesn't exist.

This throws an ArrayIndexOutOfBoundsException in the main program. JavaFX detects this and throws another InvocationTargetException, because it is unable to finish the call with reflection. Usually InvocationTargetExceptions are wrapping exceptions that wraps around another more specific exception.

**Comment by RussellDash332** [comment] 2022-09-21 08:37
I tried using the text UI testing to see what's wrong.
Here's what I did:
- Modifed `runtest.sh` on these two lines
  - `if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/duke/*.java`
  - `java -classpath ../bin duke/Duke < input.txt > ACTUAL.TXT`

I found that your `ACTUAL.txt` is not overwritten somehow, so it passes only if I put nothing on `EXPECTED.txt`.

Furthermore, if I have `deadline deadline` on `input.txt`, I get this which might help resolving your error. (Line 221 of TaskList has been stated by @rui-han-crh, this is thus a further verification)
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at duke.TaskList.addDeadlineTask(TaskList.java:221)
        at duke.TaskList.addTaskType(TaskList.java:196)
        at duke.Parser.editTask(Parser.java:112)
        at duke.Parser.reply(Parser.java:93)
        at duke.Ui.run(Ui.java:31)
        at duke.Duke.run(Duke.java:41)
        at duke.Duke.main(Duke.java:61)
```

**Comment by ChongCheeKaiClarence** [comment] 2022-09-21 10:47
@rui-han-crh @RussellDash332 Thanks for the help! It's working.

**Closed as completed** 2022-09-21 13:59 UTC
Labels: type-HelpRequest :sos:, suitableForPeerHelp
